# Generated by Django 6.0.3 on 2026-03-10 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('EXAMS', 'Exams'), ('LECTURES', 'Lectures/Schedules'), ('EVENTS', 'Events'), ('SCORES', 'Exam Scores / Supplementary Results'), ('GENERAL', 'General')], default='GENERAL', max_length=10)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/attachments/')),
                ('is_important', models.BooleanField(default=False)),
                ('view_password', models.CharField(blank=True, help_text='Optional: Set a password for sensitive Exam Score notices.', max_length=50)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
