# Generated by Django 6.0.3 on 2026-03-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_author_alter_notice_view_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notices/attachments/')),
                ('file_name', models.CharField(help_text='Example: Chapter 1, Full Report, etc.', max_length=100)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notices.notice')),
            ],
        ),
    ]
